### PR TITLE
client pop-up error management

### LINKED ISSUE #76: Client pop-up error management and display
The client should have all possible error saved in it's logic and we should have a few ways to handle each error:

- "_POP-UP_" error that will be shown in a designated component
- "_TOOLTIP_" errors that will appear next to inputs if wrong input was entered
- "_behind the scenes_" error that will not appear to the user

### PR DESCRIPTION
**Pull request by ZimGil**
The client is now capable of managing "_POP-UP_" errors

tooltip errors will still be part of the template for now.
We could change them to _pop-up_ at any time.

resolves #76

### CODE REVIEW

File: src/app/models/pop-up-error.interface.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+export interface PopUpError {
+    errorText: string;
+    errorDescription?: string;
+    handleFunction?: Function;
+    callingObject?: Object;
```
Comment (ortichon) [inline src/app/models/pop-up-error.interface.ts]: maybe change `callingObject` to `scope` ?

File: src/app/services/error/error.service.ts [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+  clearError(error: PopUpError): void {
+    this.errors.splice(this.errors.indexOf(error), 1);
+  }
+
+  isErrors(): boolean {
+    return this.errors === [] ? false : true;
+  }
+
+  handleError(error: PopUpError): void {
+    error.handleFunction.call(error.callingObject);
```
Comment (ortichon) [inline src/app/services/error/error.service.ts]: `handleFunction` is optional prop... please check if it exists before you use it.

File: src/app/app.component.ts [hunk 3]
```diff
@@ -20,9 +22,10 @@ export class AppComponent implements OnInit {
   timedStatusCheck = interval(1000);
   subscription = {};
   isAlive = true;
-  isProjectLeavable = true;
 
-  constructor(private commandService: CommandService) {}
+  constructor(
+    private commandService: CommandService,
+    private errorService: ErrorService) {}
```
Comment (ortichon) [inline src/app/app.component.ts]:
```typescript
constructor(
    private commandService: CommandService,
    private errorService: ErrorService
) {}
```

File: src/app/app.component.ts [hunk 4]
```diff
@@ -108,4 +115,7 @@ export class AppComponent implements OnInit {
     });
   }
 
+  addError(error: PopUpError): void {
```
Comment (ortichon) [inline src/app/app.component.ts]: you don't use this method

File: src/app/app.component.ts [hunk 5]
```diff
@@ -78,24 +82,35 @@ export class AppComponent implements OnInit {
...
   keepAlive(): void {
-    this.subscription['keepAlive'] = this.timedStatusCheck
-      .subscribe(() => {
-        this.commandService.keepAlive()
-          .subscribe( response => {
-            this.isAlive = true;
-          }, error => {
-            this.isAlive = false;
-            this.subscription['keepAlive'].unsubscribe();
+    console.log('keep alive sending');
```
Comment (ortichon) [inline src/app/app.component.ts]: remove log

File: src/app/models/pop-up-error.interface.ts [hunk 6]
```diff
@@ -0,0 +1,6 @@
+export interface PopUpError {
+    errorText: string;
+    errorDescription?: string;
+    handleFunction?: Function;
+    callingScop?: Object;
```
Comment (ortichon) [inline src/app/models/pop-up-error.interface.ts]: scope
